name: Keep App Awake

on:
  schedule:
    # Gira ogni 4 ore
    - cron: '0 */4 * * *'
  workflow_dispatch: 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Sveglia App
        run: |
          curl -I -L -s "https://test-la-riunione-poteva-essere-una-mail.streamlit.app/"
