name: Keep App Awake

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch: 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Sveglia forzata
        run: |
          curl -L -s -o /dev/null -w "%{http_code}" "https://test-la-riunione-poteva-essere-una-mail.streamlit.app/" || true
