name: Keep App Awake

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch: 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Sveglia App
        run: curl -sL "https://test-la-tiunione-poteva-comunicattivamente.streamlit.app" > /dev/null
